### ISSUE TITLE
Promoted tweets visible in Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [Hendriksie/Hide-promoted-tweets#1]
After adding version 1.0.4 to Waterfox 56.2.10, I still see promoted tweets near the head of https://twitter.com/waterfoxproject

![image](https://user-images.githubusercontent.com/192271/57974868-72973900-79b7-11e9-8c9d-da5c0ee494fe.png)

The same with version 1.0.

**Comment by Hendriksie** [comment]
@grahamperrin Addon has been updated to hide promoted tweets with the new redesign op Twitter. Can you please try again?

**Comment by grahamperrin** [comment]
Confirmed, thanks, working with Waterfox Classic 56.2.12 at both https://twitter.com/home and https://mobile.twitter.com/home
