### ISSUE TITLE
doesn't work with new twitter design

### ISSUE THREAD

**Issue by weedcoder** [Hendriksie/Hide-promoted-tweets#2]
twitter made a lot of changes in its new interface. it probably changes a lot of code, html and css.
my personal user experience with the new twitter made me notice this firefox module doesn't work anymore.
@Hendriksie are you working on something or do we have to uninstall the module in firefox?

**Comment by Hendriksie** [comment]
@weedcoder I will look at this issue this weekend or next week. I'm still on the old interface so I didn't notice.

**Comment by weedcoder** [comment]
it's not "advertised" in your project, but removing promoted tweets gives a visible performance boost. just saying.

**Comment by Hendriksie** [comment]
@weedcoder Do you happen to have a few example profiles where promoted tweets are visible? I can't seem to find any on my Firefox, Chrome and Edge with add-ons disabled 🤔 

> it's not "advertised" in your project, but removing promoted tweets gives a visible performance boost. just saying.

It does require me to get the 'scripting' permission from the user to do this, I'm not sure if I want to ask that. What do you think?

**Comment by weedcoder** [comment]
![new-twitter-sponsorised](https://user-images.githubusercontent.com/4971940/62010994-bd30f080-b172-11e9-89a6-f3db2cc21cac.png)
ads are pretty rare in timelines for now.
if you want to see some of them, go to a profile.

**Comment by Hendriksie** [comment]
@weedcoder Will try to search for some profiles, so far I don't see anything.

Is it possible for you to inspect the Sponsored element and see what classes are assigned?

**Comment by Hendriksie** [comment]
I've finally seen a sponsored tweet in the new redesign. I've played around a bit and so far I see this CSS selector would hide all sponsored tweets: `.css-1dbjc4n > .css-1dbjc4n > .css-1dbjc4n > article.css-1dbjc4n`. The classes seem to be all random gibberish so I'm not sure if these CSS rules will work in the future.

**Comment by Hendriksie** [comment]
@weedcoder addon has been updated: https://addons.mozilla.org/en-US/firefox/addon/hide-promoted-tweets/

Can you update the addon and try again to see if you still see promoted tweets?

**Comment by weedcoder** [comment]
updated! i saw the "who to follow thing" but no ad. it seems to work. i will feed back if i see ads. thank you a lot! :pray:

**Comment by weedcoder** [comment]
and... performance boost again, yeah! :tada:
